### ISSUE TITLE
[Improvement]: Correct behavior when running `project start`

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1155]
### Describe the improvement

Currently, when your own project is running, you get
```
$ cargo shuttle project start
Error: 400 Bad Request
message: a project with the same name already exists
```
which is correct, but it would be better if it behaved differently when you are the owner of that project.

### Suggested Solution:

Output a different error message if you are the owner, such as `project is already running`.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by ivandardi** [comment]
I'm taking a look at this!

**Comment by ivandardi** [comment]
I decided to rescind my assignment on this issue. I originally started working on this to familiarize myself with the Shuttle codebase, but I unfortunately currently don't have a job that provides me the time nor money to contribute to open source projects that I'm excited about.

**Comment by d4ckard** [comment]
Hey, I'd like to work on this issue. 🙋

**Comment by d4ckard** [comment]
I have just  started looking into the origin of the current behavior. The error message we have right now is generated in two places. It is  represented by the `shuttle-gateway` `ErrorKind::ProjectAlreadyExists`.

1. `GatewayService::create_project` in `gateway/src/service.rs`. Here the error  is always returned if an existing project is found and this project is not destroyed. In that case, I need to figure out how to determine whether the caller is the owner of the  project to change the error message. Some guidance on how to do so would help me a lot here I think.
2. `GatewayService::insert_project` in `gateway/src/service.rs`. If the SQL `insert` query that this function failed because the name of the project already exists in the database, the error is returned, too. However, I don't think we are given the actual database entry here so we have less information to work with to determine the owner of the project.

I think I'll start digging into `create_project` tomorrow first. Again, I'd be glad about any suggestions to point me in the right direction.

**Comment by jonaro00** [comment]
In (1), the first if-clause is, as the comment states, actually only reached if the account name matched in the SQL query as well. Therefore, that else clause where the error is returned happens "if project exists, and the account name matches, but the project is not destroyed".
I believe updating that error to a new variant as stated above is the only thing required. Although `project is already running` might not be true. It would also be nice if the current state of the project was embedded in the error, like the way `cargo shuttle status` shows.

**Comment by d4ckard** [comment]
Thanks for pointing out this detail about the SQL query. It looks like `insert_project` is only used in the else-clause of this query in the `create_project` function. This means that `insert_project` only every returns a `ProjectAlreadyExists` error if the existing project is not owned by the caller. If it is, then the query in `create_project` should have returned true and `insert_project` would not have been called. This supports your suggestion of replacing the current error with a new variant in `create_project`.
Also, is `insert_project` used anywhere else? It's public but I couldn't find any other occurrence in this repo.

**Comment by jonaro00** [comment]
Sounds good. Also don't see another occurrence.
