### ISSUE TITLE
[Improvement]: Fix ProjectName validation

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1223]
Continuation of the task described in https://discord.com/channels/803236282088161321/1052364653373702235/1150824517548134531

1. Merge the ProjectName types so that it is only defined in common. Use the good parts from gateway (no uppercase, sqlx derive) and the good parts from #418 (reserved names, doc string, tests, etc) to common.
2. Gateway's imports of ProjectName can be redirected to common, and should be a clean replacement.
3. Cargo-shuttle can still use the type, but should never validate a string wrapped in it. Same for other user-facing crates.
   -  Beware that #1050 is getting merged soon (probably before this), and there are some touches on its uses there, so don't get too ahead of yourself.
4. Check that gateway validates the project name where necessary.

Let me know if I forgot something.
GLHF💪

**Comment by d4ckard** [comment]
Hey, I'd like to work on this one.

**Comment by d4ckard** [comment]
Regarding (3), I don't think that it really matters whether client-side code ever uses the `ProjectName` type to validate the name. What's important is that the gateway never accepts invalid names. That is, it should not depend on the client to do the validation.

Also doing the validation on the client-side has the advantage, that people get feedback on their names more quickly than waiting for the gateway to respond.

That's why I'd consider just putting the validation in constructor for `ProjectName`, so that we know that all `ProjectName`s are valid already.
