### ISSUE TITLE
[Bug]: Failed deployment with index errors

### ISSUE THREAD

**Issue by techs-sus** [shuttle-hq/shuttle#1385]
### What happened?

When running `cargo shuttle deploy` (or using the github action), the build fails with a index error.

### Version

v0.32.0

### Which operating system(s) are you seeing the problem on?

In deployment

### Which CPU architectures are you seeing the problem on?

In deployment

### Relevant log output

```sh
{error="Build error: `cargo metadata` exited with an error:     Updating `shuttle-crates-io-mirror` index\nerror: failed to select a version for the requirement `itertools = \"^0\"` (locked to 0.12.0)\ncandidate versions found which didn't match: 0.11.0, 0.10.5, 0.10.4, ...\nlocation searched: `shuttle-crates-io-mirror` index (which is replacing registry `crates-io`)\nrequired by package `project v0.1.0 (/opt/shuttle/shuttle-builds/project)`\nperhaps a crate was updated and forgotten to be re-vendored?\n"} Service build encountered an error
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by techs-sus** [comment]
Also, it says "failed to fetch crates" which could imply the Deployer is not correctly fetching crates.

**Comment by jonaro00** [comment]
This error happens due to our crates-io mirror not having the latest version of a crate. The crate was released 11 hours ago at the time of writing, so it is strange that our mirror does not have it yet.
To temporarily resolve this, you can either revert the lock file to an older one (if you have that option), or add a version lock  to an older version, for example `itertools = "=0.11.0"`.
We will investigate why the mirror is falling behind.

**Comment by jonaro00** [comment]
We have corrected the issue and started syncing the mirror again. It should be possible to use new crates now.
