### ISSUE TITLE
feature: run shuttle on Kubernetes

### ISSUE THREAD

**Issue by christos-h** [shuttle-hq/shuttle#169]
Shuttle currently runs on AWS via terraform config.

Deploying on Kubernetes would offer non-cloud, cross-cloud and alternative cloud provider support.

**Comment by Xavientois** [comment]
We might consider using Helm charts to modularize the IaC if we switch to using Kubernetes

**Comment by Christof23** [comment]
Hi, what's the current status for this issue? I'd like to be able to use shuttle to deploy apps to self-hosted kubernetes clusters.

**Comment by tukanoidd** [comment]
> Hi, what's the current status for this issue? I'd like to be able to use shuttle to deploy apps to self-hosted kubernetes clusters.

I've been trying to find any info on shuttle self-hosting, but it seems like it's still a "planned to be available in the future" thing, probably after it's considered production-ready by the main team (according to README it's not there yet)

**Comment by eslavnov** [comment]
Hi everyone, thank you for your questions and feedback - this is very much appreciated and helps us prioritize our product development efforts 🙏.

Kubernetes support is something we have indeed considered for a while, but at this point we do not have any concrete plans to implement this due to complexity of such a project.

For the broader topic of self-hosting Shuttle, we currently support running Shuttle app on your local system: [https://docs.shuttle.rs/getting-started/local-run](https://docs.shuttle.rs/getting-started/local-run). 

We also have Bring Your Own Cloud on our long-term roadmap, but at this point we are not ready to share any particular timelines for this feature.
