### ISSUE TITLE
feature: support custom domain

### ISSUE THREAD

**Issue by christos-h** [shuttle-hq/shuttle#171]
Currently shuttle apps are automatically provisioned a subdomain, for example 'my-app.shuttleapp.rs'. This feature adds the ability to support user-owned domains, 'my-app.com'.

**Comment by BadgerBloke** [comment]
Hi @christos-h I would like to work on this. Can you please assign this to me.

**Comment by oddgrd** [comment]
Hey @BadgerBloke, thanks for showing interest in working on this! This has actually already been implemented, or at least the infrastructure for it has, but it's not a publicly available feature. We're planning for this feature to be released as part of our pro tier.

**Comment by ShayBox** [comment]
I thought the pro/paid tiers would have been released back when there was publicity around Shuttle, it seems like that momentum was not taken advantage of and mostly lost.

**Comment by ivancernja** [comment]
Hello @ShayBox!

I appreciate your concern regarding the timing of the paid tiers release. It's important to keep in mind that we want to thoroughly test and refine the tiers to minimize the chance of unexpected issues or user dissatisfaction, especially given the unique nature of the user experience when transitioning from free to paid usage.

In regards to the momentum; we don't feel like any momentum has been lost since the start of our paid tiers testing phase but even if there was a loss of momentum, we'd rather take that approach than deliver a subpar solution to our users.

All-in-all, we are __very__ close to releasing our pricing model and we'd love to have you onboard of the final paid tier testing phase if you'd be down! :)

**Comment by jonaro00** [comment]
Update: Pro users can now add custom domains. Full automation of this feature is planned.

**Comment by jonaro00** [comment]
Closing in favour of #1562
