### ISSUE TITLE
[Improvement]: Bump sqlx to 0.8 in libraries

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1838]
### Describe the improvement

- Bump sqlx to 0.8.0 in `resources/aws-rds` and `resources/shared-db`
- Also bump sqlx in all examples that use it, and verify that they still compile on a local run using patches (check DEVELOPING.md)

This will result in 2 PRs, one in this repo, one in shuttle-examples.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by sentinel1909** [comment]
I'd be happy to take this one and get 'er done.

**Comment by sentinel1909** [comment]
I've started working this issue. Is it desired to update to sqlx 0.8.0 at the workspace level? I ask because, after opening a new branch I which to work, I changed the dependency at the workspace level and immediately hit trouble in resources..

I'll post a snip of the specifics a bit later.  Just want to confirm the scope of work, so to speak.

**Comment by jonaro00** [comment]
No, bumping it in the workspace will require a lot more work.
The crates listed are not members of the workspace.

Just noticed that diesel-async 0.5.0 is also available. If you get done with sqlx, you can take a stab at that as well (same thing, but no examples need updates).

**Comment by sentinel1909** [comment]
Alright...I'm a little embarrassed, but it's been awhile since I worked on the code base. Do I have to spin up locally when testing?  I did `cargo test` from the project root, half the tests passed and half failed...figured I must be missing something.

Just need a pointer or two to set off in the right direction here.

Thanks,

~Jeff

**Comment by jonaro00** [comment]
Since they are not workspace members, you need to cd to their directories before using cargo commands.
The crates in question don't have tests, but they need to compile with various sets of feature flags.
Our CI, which will run when you make the PR, should cover the needed cases.

**Comment by sentinel1909** [comment]
Pull request submitted. Will work on `shuttle-examples` next.
