### ISSUE TITLE
Stop current deployment

### ISSUE THREAD

**Issue by plumsirawit** [shuttle-hq/shuttle#614]
I may be stupid, but after some time looking on the docs and the CLI, I can't seem to find any way to stop (or pause) the current deployment. The closest command is `cargo shuttle delete` but I'm too afraid to do that because it looks like it will delete the whole service.

Is there a way to halt the currently running deployment?

**Comment by joshua-mo-143** [comment]
Hi there!

Currently at the moment, the quickest way to stop the current deployment is by using `cargo shuttle project rm` which stops the container your deployment is on until you decide to deploy again.

**Comment by plumsirawit** [comment]
It looked fine until uhhh...

![image](https://user-images.githubusercontent.com/31605957/217029078-d64f61fd-05d7-4639-9cc1-d6b2f94325dc.png)

**Comment by joshua-mo-143** [comment]
Try using `cargo shuttle project rm` again - there are currently some kinks being worked out with deployments sometimes partially not shutting down correctly. Not entirely sure what the ETA is on the fix, but yeah

**Comment by plumsirawit** [comment]
Well actually it's ok now since I actually just did create another project with a different name. Hmm... now I have a different problem...

**Comment by Mautriz** [comment]
Ill take a look and try to implement this as sono as I have time this week

**Comment by Mautriz** [comment]
Hey there, I just started looking into the issue, after a first look at the project there seem to be already a `Stopped` state on deployments

Seems like the idea would be to just add stop/restart commands and relative endpoints that change and persist that state (which I'm not sure of as I still have to look up what will the Stopped state imply)

I'll probably find something new, am I going in the right direction ? Can I ask someone in particular in case I'd need some help ?

**Comment by oddgrd** [comment]
Hey! Apologies for the late reply, we've been busy with a release. This issue is quite complicated and I haven't looked into it for a bit, but I can give you some leads. @chesedo may have more insight when he gets a moment. 

So the jist of it is we do currently have a command for stopping the current deployment, and it works in every way except for actually stopping the service.  Even if we use the kill sender to drop the handle to the deployment, the deployments task lives on. You should be able to see this if you run locally with `tokio-console`. 

For a code lead, IIRC this is the root of the issue: https://github.com/shuttle-hq/shuttle/blob/main/service/src/lib.rs#L472-L479

Sorry I can't give you more information atm, but I hope this helps!

**Comment by chesedo** [comment]
The code @oddgrd links to is the reason deployments are not being stopped because that `tokio::Runtime` never gets dropped. If we were to remove the `std::mem::forget()` then the runtime will be dropped by `Bootstrapper::into_handle()`. But this will kill the runtime prematurely. So the solution will be to somehow keep the runtime around until the kill signal is send to the kill channel in `DeploymentManager` and to only then drop it.

**Comment by jonaro00** [comment]
Had a quick look at the related code. Here is a careless proposal:

Make ServerHandle a struct that holds the JoinHandle and the Runtime.
Let Binder take ownership of Runtime and give it to the ServerHandle.
The spawned task in Loader.load can then hold the runtime until after the bootstrapper's handle is done.

I have a very incomplete understanding of this so there are probably flaws with my approach, but perhaps it is in the right direction.
What do you think?

**Comment by oddgrd** [comment]
@jonaro00 It might, but I'd have to take a closer look to give a proper answer. Did you try it? It would be great to have this fixed now, but we are working on refactoring from loading projects as dynamic libraries to compiling projects to binaries and starting them. And at that point, this problem should be solved. But it could be a little while.

**Comment by oddgrd** [comment]
This should be resolved after 0.12, but please re-open this if you still experience it. Thanks!
