### ISSUE TITLE
Add support for S3 objects

### ISSUE THREAD

**Issue by brokad** [shuttle-hq/shuttle#668]
Currently, for ad-hoc persistent storage, we only support local volumes. We'd like to add support for S3 object storage. The user-facing API should follow the same entrypoint as other [resources](https://docs.shuttle.rs/resources/shuttle-shared-db). IOW, there should be a new plugin crate allowing the proc-macro to support adding S3 clients from the [aws-sdk-s3](https://docs.rs/aws-sdk-s3/0.24.0/aws_sdk_s3/) crate to the arguments of a `shuttle_runtime::main` function.

I can think of a rough plan to deliver this (which could be separate but complete PRs):
- Add the required methods to [provisioner](https://github.com/shuttle-hq/shuttle/tree/main/provisioner) to create/delete buckets. (started in #685, which is no longer in progress, but we should be able to use some of the work done there.)
- Create a plugin crate (as mentioned above) in the same fashion as other [resources](https://github.com/shuttle-hq/shuttle/tree/main/resources), this will also require updating the [Factory](https://github.com/shuttle-hq/shuttle/blob/main/service/src/lib.rs#L78) trait and it's implementations to make it able to request S3 storage.

After this, we also have to update the local provisioner in [cargo-shuttle](https://github.com/shuttle-hq/shuttle/blob/main/cargo-shuttle/src/provisioner_server.rs), which requires thinking about how we want this to work in a local run. Should we use the users ambient AWS credentials and provision the resource on their own account? Or should we use an [S3 mock server](https://hub.docker.com/r/adobe/s3mock/)?

Our terraform repository is private (it will be made public in the future), but editing our terraform is not required for this PR. This PR should however indicate which roles are needed to create the S3 buckets.

**Comment by dphov** [comment]
@ivancernja @brokad I'm interested to collaborate with you on this issue

**Comment by dphov** [comment]
@oddgrd I'm sorry, but I will step down from this task, too many constraints for me at this moment.

**Comment by Shubham8287** [comment]
Hi, I am actively looking to contribute to Shuttle. I also read some code base already, I would love to pick this up and I will start by sharing my approach in couple of days, please assign this to me.

**Comment by oddgrd** [comment]
No worries @dphov, thanks for all your effort! I hope to see you again in the future.

@Shubham8287 cool, sounds good! Feel free to reach out in our discord in the #contributors channel if you have questions.

**Comment by ibrahim-akrab** [comment]
Hey @Shubham8287 , are you still working on this?

**Comment by Shubham8287** [comment]
Hi @ibrahim-akrab , yes I am working on it. Planned to share a draft PR by today.

**Comment by ibrahim-akrab** [comment]
That's great news، good luck 👍

**Comment by Shubham8287** [comment]
I think I understood most of the code changes required for the task,  Already halfway to the implementation. So, Trying to write my high-level approach to get some feedback.
1. I started by creating a new rocket example, This example can act as e2e test for finishing the issue.
2. `aws_sdk_s3` provides an stateless client (you need to pass the bucket name as arg each time) to manage buckets/objects. I can create a custom Struct with bucket info over `aws_sdk_s3` to handle calls for buckets. This Struct will implement a few methods which will be exposed to end users to manage buckets in the shuttle.
3. Implement a ResourceBuilder for custom object created in step 2 in `/resources`,  where  `output`  method will create a new bucket and return credentials/info about it as config and `build` method will return an instance of our S3 custom object.
4. As Resource builder is client side code (goes in to users crate) and do not talk to the outer world directly, We need to make a change in the Provisioner factory and proto to add new methods to provision bucket for s3 resource crate.
5. I am leaving the code for local run as `unimplemeted!()`, will get back to it later.


let me know, if you have any reviews or questions, I was sick last week but PR is in WIP, so will raise it soon.

**Comment by chesedo** [comment]
>     2. Let deployer access their bucket - I think we need something similar like connection strings for databases,  I am currently checking out STS - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html . Let me know, if you have more context about STS and if it can be used else I will update the conversation with my findings.


Yip, STS seems to be the post option for now

**Comment by iulianbarbu** [comment]
As a small update on the state of things here:

Shuttle is working inside a single AWS account and the way of providing Shuttle-managed resources to users involves creating dedicated resources per project, inside this single AWS account, which works fine for AWS RDS for example since every user project can have a dedicated RDS instance. 

However, S3/DynamoDB are global services where these user environments should still exist, but to make that happen we have a few options that compromise the security of the platform (when it comes to resource provisioning) based on the current architecture. There are also open questions around how much control to give to users over these global services: e.g. for S3, give users access to S3 to create how many buckets they want and have access only over those through AWS SDK or create S3 buckets on behalf of the users, and find a way to give them access to those buckets, but balance this out with the current users systems and try to not introduce friction in using the old ways with Shuttle.

All of the above has a dependency on some more design work that is tightly coupled with some of the re-architecture efforts that would allow us to scale more and provide better multi-tenancy, which is still underway.

**Comment by jonaro00** [comment]
Closing in favour of #1565
