### ISSUE TITLE
Create a GitHub action

### ISSUE THREAD

**Issue by brokad** [shuttle-hq/shuttle#87]

**Comment by AugustoFKL** [comment]
Any other descriptions?

The action should do what? Since there's already 3 actions that cover CI, CD, and code valitation, there's no way to identify the action needed.

**Comment by christoshadjiaslanis** [comment]
Pining @brokad - but I believe the point of this GH action is initially to deploy a shuttle project to shuttle. So basically install `cargo-shuttle` and run `cargo shuttle deploy`.

**Comment by kaleidawave** [comment]
I created a simple action for deploying a site on shuttle

https://github.com/kaleidawave/axum-shuttle-demo/blob/main/.github/workflows/publish.yml

If you remove the `Check source` step it is pretty much ready to go. I also added `| awk '!/Database URI.*?$/'` to the end of the deploy command to remove the database uri because it contains the database password and I think GH actions logs are public.

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action is a good guide about how to package one up and https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler is a good example for a "cloud deployment GH action"

**Comment by christoshadjiaslanis** [comment]
Repo is ready -> https://github.com/shuttle-hq/shuttle-deploy-action
