### ISSUE TITLE
[Bug]: Cant deploy

### ISSUE THREAD

**Issue by MrEnder0** [shuttle-hq/shuttle#877]
### What happened?

When attempting to deploy it waits a few seconds and then returns the following.

Error: 503 Service Unavailable
message: project not ready

### Version

v0.15.0

### Which operating systems are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Hey @MrEnder0, sorry about the delayed reply. Did you create a project (`cargo shuttle project start`) before trying to deploy? [Here](https://docs.shuttle.rs/introduction/quick-start) are our getting started docs. We're also on v0.16.0 now.

**Comment by paulotten** [comment]
@oddgrd I've got the same error (and more logs) for a project I tried to deploy yesterday.

I successfully deployed it at least twice. Trying to update it one more time I got:

```
PS C:\coding\shuttle\container-explorer> cargo shuttle deploy --allow-dirty
2023-05-10T19:21:05.546926Z ERROR cargo_shuttle::client: failed to connect to websocket
Error: could not connect to websocket
Caused by:
    HTTP error: 502 Bad Gateway

2023-05-10T15:21:12.863238262Z  INFO Entering queued state
2023-05-10T15:21:12.877043006Z TRACE {uri="http://gateway:8001/stats/load"} shuttle_deployer::deployment::gateway_client: calling gateway
2023-05-10T15:21:12.881620424Z DEBUG hyper::client::pool: reuse idle connection for ("http", gateway:8001)
2023-05-10T15:21:12.891333301Z TRACE {response="Response { status: 200, version: HTTP/1.1, headers: {\"content-type\": \"application/json\", \"content-length\": \"38\", \"date\": \"Wed, 10 May 2023 19:21:11 GMT\"}, body: Body(Streaming) }"} shuttle_deployer::deployment::gateway_client: Load response
2023-05-10T15:21:12.895968643Z  INFO Entering building state
2023-05-10T15:21:13.036278080Z  INFO     Blocking waiting for file lock on package cache
2023-05-10T15:21:28.189113546Z  INFO     Blocking waiting for file lock on build directory
2023-05-10T15:22:03.610965757Z  INFO     Finished release [optimized] target(s) in 50.69s
2023-05-10T15:22:03.745874340Z  INFO     Blocking waiting for file lock on package cache
2023-05-10T15:22:11.633114488Z  INFO     Blocking waiting for file lock on package cache
2023-05-10T15:22:19.244491403Z  INFO     Blocking waiting for file lock on build directory
```

I killed the job some minutes later with control-C when I was convinced it wasn't going to complete.

Every time I've tried deploying it again since then (yesterday and today) I've gotten the following.

```
PS C:\coding\shuttle\container-explorer> cargo shuttle deploy --allow-dirty
Error: 503 Service Unavailable
message: project not ready
```

https://container-explorer.shuttleapp.rs/ returns `{"message":"project not ready","status_code":503}`

**Comment by MrEnder0** [comment]
> @oddgrd I've got the same error (and more logs) for a project I tried to deploy yesterday.
> 
> I successfully deployed it at least twice. Trying to update it one more time I got:
> 
> ```
> PS C:\coding\shuttle\container-explorer> cargo shuttle deploy --allow-dirty
> 2023-05-10T19:21:05.546926Z ERROR cargo_shuttle::client: failed to connect to websocket
> Error: could not connect to websocket
> Caused by:
>     HTTP error: 502 Bad Gateway
> 
> 2023-05-10T15:21:12.863238262Z  INFO Entering queued state
> 2023-05-10T15:21:12.877043006Z TRACE {uri="http://gateway:8001/stats/load"} shuttle_deployer::deployment::gateway_client: calling gateway
> 2023-05-10T15:21:12.881620424Z DEBUG hyper::client::pool: reuse idle connection for ("http", gateway:8001)
> 2023-05-10T15:21:12.891333301Z TRACE {response="Response { status: 200, version: HTTP/1.1, headers: {\"content-type\": \"application/json\", \"content-length\": \"38\", \"date\": \"Wed, 10 May 2023 19:21:11 GMT\"}, body: Body(Streaming) }"} shuttle_deployer::deployment::gateway_client: Load response
> 2023-05-10T15:21:12.895968643Z  INFO Entering building state
> 2023-05-10T15:21:13.036278080Z  INFO     Blocking waiting for file lock on package cache
> 2023-05-10T15:21:28.189113546Z  INFO     Blocking waiting for file lock on build directory
> 2023-05-10T15:22:03.610965757Z  INFO     Finished release [optimized] target(s) in 50.69s
> 2023-05-10T15:22:03.745874340Z  INFO     Blocking waiting for file lock on package cache
> 2023-05-10T15:22:11.633114488Z  INFO     Blocking waiting for file lock on package cache
> 2023-05-10T15:22:19.244491403Z  INFO     Blocking waiting for file lock on build directory
> ```
> 
> I killed the job some minutes later with control-C when I was convinced it wasn't going to complete.
> 
> Every time I've tried deploying it again since then (yesterday and today) I've gotten the following.
> 
> ```
> PS C:\coding\shuttle\container-explorer> cargo shuttle deploy --allow-dirty
> Error: 503 Service Unavailable
> message: project not ready
> ```
> 
> https://container-explorer.shuttleapp.rs/ returns `{"message":"project not ready","status_code":503}`

I remember something similar happening where it got stuck and I ctr-led C out of it due to it doing nothing for 5~ mins and since not being able to do anything.

**Comment by oddgrd** [comment]
Ah, I think we have another report of this where a project crashes on deploy when a deploy is already running. This is definitely a bug, but I'm not sure what causes it yet.

So when it says your project is not ready, I'm thinking the deploy crashed your project (deployer container). Did you try to do a `cargo shuttle project restart`? And then check `cargo shuttle deployment list` to see what state the last few deployments are in.

**Comment by paulotten** [comment]
`cargo shuttle project restart` seems to have worked, restarting the last version that was deployed successfully.

`cargo shuttle deployment list` shows half a dozen `stopped` deployments from `2023-05-10` and one `running` deployment from just now. It doesn't appear to list anything for the times that I got `Error: 503 Service Unavailable`.

---

Trying `cargo shuttle deploy --allow-dirty` again now it worked.

So yes, it seems like `cargo shuttle project restart` fixed this for me.

**Comment by oddgrd** [comment]
Nice! A deploy shouldn't crash a project (currently a project represents a docker container for your project), but if it does you will get `503` since the project container is unresponsive. So it will need to be restarted. We are working on a refactor of this so a user will not need to concern themselves with the project containers (the whole `project stop`/`project start` flow), they'll just need to run `deploy`.

The reason it crashed in this instance may be that you exited the build log stream, but it was still building (or at least it was still trying), exiting the deploy command does not cancel it. The new deploy will then also start trying to build, since we don't handle multiple deployments started at the same time currently (other than that when one deployment is ready to start and about to be promoted to Running, it will stop any other running deployment, there should only be one Running at any time). We are also going to handle this better in the upcoming refactor, but it's very much a WIP :smile:
